import Head from "next/head";
import Header from "../Header";
import { useRouter } from "next/router";
import Footer from "../Footer";

export default function Layout({ children, title = "Shippr Ecommerce" }) {
    const router = useRouter();
    const pathname = router.pathname;

    return (
        <div className="app-main">
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header />

            <main className={pathname !== "/" ? "main-page" : ""}>{children}</main>

            <Footer />
        </div>
    );
}
