import Head from "next/head";
import Header from "../Header";
import { useRouter } from "next/router";
import Footer from "../Footer";
import BottomNavigation from "../Mobile/MobileBottomNavigation";
import { ScreenContext } from "../../contexts";
import { useContext } from "react";
import { Loading } from "..";

export default function Layout({ children, title = "Shippr Ecommerce", status }) {
  const router = useRouter();
  const pathname = router.pathname;
  const { mobileScreen } = useContext(ScreenContext);

  return (
    <div className={`${!mobileScreen ? "app-main" : "mobile-main"}`}>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className={pathname !== "/" ? "main-page" : ""}>{status?.isLoading ? <Loading /> : children}</main>

      <div className="relative">{mobileScreen ? <BottomNavigation /> : <Footer />}</div>
    </div>
  );
}
